Repository oracle/spring-cloud-oracle, pull requests merged in 2024-08, with the labels that each got.

#92 SpringBoot test for TEQ
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/TEQPartitionIT.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/TEQSpringBootIT.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/Util.java
Labels: OCA Verified

#93 Enable 'mvn integration-test'
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  spring-cloud-oci/pom.xml
Labels: OCA Verified

#94 Fix links
  spring-cloud-oci/docs/src/main/asciidoc/adb.adoc
  spring-cloud-oci/docs/src/main/asciidoc/email.adoc
  spring-cloud-oci/docs/src/main/asciidoc/function.adoc
  spring-cloud-oci/docs/src/main/asciidoc/genai.adoc
  spring-cloud-oci/docs/src/main/asciidoc/getting-started.adoc
  spring-cloud-oci/docs/src/main/asciidoc/logging.adoc
  spring-cloud-oci/docs/src/main/asciidoc/notifications.adoc
  spring-cloud-oci/docs/src/main/asciidoc/queues.adoc
  spring-cloud-oci/docs/src/main/asciidoc/storage.adoc
  spring-cloud-oci/docs/src/main/asciidoc/streaming.adoc
  spring-cloud-oci/docs/src/main/asciidoc/vault.adoc
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/test/java/com/oracle/cloud/spring/sample/storage/springcloudocistoragesample/SpringCloudOciStorageSampleApplicationTests.java
Labels: documentation, OCA Verified

#95 Version upgrades and timeout resolution for MAC M1
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/TEQPartitionIT.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/Util.java
Labels: enhancement, OCA Verified

#97 update 1.2.0 doc branding
  docs/src/main/asciidoc/_attributes.adoc
  docs/src/main/asciidoc/adb.adoc
  docs/src/main/asciidoc/core.adoc
  docs/src/main/asciidoc/email.adoc
  docs/src/main/asciidoc/function.adoc
  docs/src/main/asciidoc/genai.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/index-docinfo.xml
  docs/src/main/asciidoc/index.adoc
  docs/src/main/asciidoc/logging.adoc
  docs/src/main/asciidoc/notifications.adoc
  docs/src/main/asciidoc/queues.adoc
  docs/src/main/asciidoc/storage.adoc
  docs/src/main/asciidoc/streaming.adoc
Labels: OCA Verified

#98 publish docs
  1.2.0/reference/html/adb.html
  1.2.0/reference/html/appendix.html
  1.2.0/reference/html/configuration.html
  1.2.0/reference/html/core.html
  1.2.0/reference/html/db_starters.html
  1.2.0/reference/html/email.html
  1.2.0/reference/html/function.html
  1.2.0/reference/html/genai.html
  1.2.0/reference/html/getting-started.html
  1.2.0/reference/html/index.html
  1.2.0/reference/html/logging.html
  1.2.0/reference/html/notifications.html
  1.2.0/reference/html/queues.html
  1.2.0/reference/html/storage.html
  1.2.0/reference/html/streaming.html
  1.2.0/reference/html/vault.html
  latest/reference/html/adb.html
  latest/reference/html/appendix.html
  latest/reference/html/configuration.html
  latest/reference/html/core.html
  latest/reference/html/db_starters.html
  latest/reference/html/email.html
  latest/reference/html/function.html
  latest/reference/html/genai.html
  latest/reference/html/getting-started.html
  latest/reference/html/index.html
  latest/reference/html/logging.html
  latest/reference/html/notifications.html
  latest/reference/html/queues.html
  latest/reference/html/storage.html
  latest/reference/html/streaming.html
  latest/reference/html/vault.html
Labels: OCA Verified

#99 txeventq: use spring cloud parent pom
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
Labels: OCA Verified

#100 txeventq: document integration test suite
  database/spring-cloud-stream-binder-oracle-txeventq/README.md
Labels: OCA Verified

#102 initialize samples directory for database starters
  database/starters/oracle-spring-boot-starter-samples/pom.xml
  database/starters/pom.xml
Labels: OCA Verified

#103 update readme
  README.md
Labels: OCA Verified

#105 Database starters 24.2.0
  database/starters/oracle-spring-boot-starter-aqjms/pom.xml
  database/starters/oracle-spring-boot-starter-json-collections/pom.xml
  database/starters/oracle-spring-boot-starter-samples/oracle-spring-boot-sample-ucp-jpa/pom.xml
  database/starters/oracle-spring-boot-starter-samples/pom.xml
  database/starters/oracle-spring-boot-starter-ucp/pom.xml
  database/starters/pom.xml
Labels: OCA Verified

#106 Update JDBC version
  database/starters/pom.xml
Labels: OCA Verified

#107 TxEventQ Stream Binder Sample
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/README.md
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/pom.xml
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/main/java/com/oracle/cstream/sample/StreamConfiguration.java
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/main/java/com/oracle/cstream/sample/TxEventQSampleApp.java
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/main/java/com/oracle/cstream/sample/WordSupplier.java
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/main/resources/application.yaml
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/test/java/com/oracle/cstream/sample/TxEventQSampleAppTest.java
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/src/test/resources/init.sql
  database/spring-cloud-stream-binder-oracle-txeventq/src/main/java/com/oracle/cstream/TxEventQQueueProvisioner.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/main/java/com/oracle/cstream/utils/SpecCompliantJmsHeaderMapper.java
  database/starters/scripts/deploy
Labels: OCA Verified

#108 Add Stream Binder to main README
  README.md
Labels: OCA Verified

#109 fix typo
  database/spring-cloud-stream-binder-oracle-txeventq/README.md
Labels: OCA Verified
