Repository oracle/spring-cloud-oracle, pull requests merged in 2024-07, with the labels that each got.

#50 POM Distribution management
  pom.xml
  spring-cloud-oci-dependencies/pom.xml
Labels: OCA Verified

#51 Override Parent POM distribution management
  docs/pom.xml
  pom.xml
  spring-cloud-oci-dependencies/pom.xml
Labels: OCA Verified

#52 Deploy javadoc, sources
  pom.xml
  scripts/deploy
Labels: OCA Verified

#53 Deploy TPL, License files
  pom.xml
  scripts/deploy
Labels: OCA Verified

#44 Support for Autonomous Database
  docs/src/main/asciidoc/adb.adoc
  pom.xml
  spring-cloud-oci-adb/pom.xml
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDb.java
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDbDetails.java
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDbImpl.java
  spring-cloud-oci-adb/src/test/java/com/oracle/cloud/spring/adb/AutonomousDbImplTests.java
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/adb/AutonomousDbAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-oci-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-adb-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-adb-samples/src/main/java/com/oracle/cloud/spring/sample/adb/springcloudociadbsample/AdbController.java
  spring-cloud-oci-samples/spring-cloud-oci-adb-samples/src/main/java/com/oracle/cloud/spring/sample/adb/springcloudociadbsample/HelloController.java
  spring-cloud-oci-samples/spring-cloud-oci-adb-samples/src/main/java/com/oracle/cloud/spring/sample/adb/springcloudociadbsample/SpringCloudOciAdbSampleApplication.java
  spring-cloud-oci-samples/spring-cloud-oci-adb-samples/src/main/resources/application.properties
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
Labels: OCA Verified

#54 Print uploaded artifacts
  scripts/deploy
Labels: OCA Verified

#57 Vault property source
  docs/src/main/asciidoc/vault.adoc
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/autoconfigure/core/RegionProviderAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultEnvironmentPostProcessor.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultProperties.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertyLoader.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertySource.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertySourceProperties.java
  spring-cloud-oci-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/main/java/com/oracle/cloud/spring/sample/vault/springcloudocivaultsample/VaultController.java
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/main/resources/application.properties
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/main/resources/application.yaml
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/test/java/com/oracle/cloud/spring/sample/vault/springcloudocivaultsample/VaultIT.java
Labels: OCA Verified

#58 update javadoc plugin version to fix issue with incorrect source version
  database/starters/pom.xml
  pom.xml
Labels: OCA Verified

#60 Spring asciidoc pom update
  .gitignore
  docs/pom.xml
  docs/src/main/asciidoc/adb.adoc
  docs/src/main/asciidoc/aqjms.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/index-docinfo.xml
  docs/src/main/asciidoc/index.adoc
  docs/src/main/asciidoc/ucp.adoc
Labels: documentation, OCA Verified

#61 fixed typo in spring-cloud-oci-adb
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDb.java
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDbImpl.java
Labels: bug, OCA Verified

#62 version and index update
  docs/pom.xml
  docs/src/main/asciidoc/index.adoc
Labels: documentation, OCA Verified

#63 VaultTemplate refactor
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/vault.adoc
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultEnvironmentPostProcessor.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertyLoader.java
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/main/java/com/oracle/cloud/spring/sample/vault/springcloudocivaultsample/VaultController.java
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/src/test/java/com/oracle/cloud/spring/sample/vault/springcloudocivaultsample/VaultTemplateIT.java
  spring-cloud-oci-vault/src/main/java/com/oracle/cloud/spring/vault/VaultTemplate.java
  spring-cloud-oci-vault/src/main/java/com/oracle/cloud/spring/vault/VaultTemplateImpl.java
  spring-cloud-oci-vault/src/test/java/com/oracle/cloud/spring/vault/VaultTemplateImplTest.java
Labels: OCA Verified

#65 Vault Autoconfiguration
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultEnvironmentPostProcessor.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertySource.java
Labels: OCA Verified

#59 Version 1.2.0
  docs/pom.xml
  pom.xml
  scripts/deploy
  spring-cloud-oci-adb/pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-function/pom.xml
  spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci-logging/pom.xml
  spring-cloud-oci-notification/pom.xml
  spring-cloud-oci-queue/pom.xml
  spring-cloud-oci-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/pom.xml
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci-storage/pom.xml
  spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci-vault/pom.xml
Labels: OCA Verified

#66 Storage uses plain Object Storage URLs
  docs/src/main/asciidoc/storage.adoc
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/main/java/com/oracle/cloud/spring/sample/storage/springcloudocistoragesample/ImageController.java
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/main/java/com/oracle/cloud/spring/sample/storage/springcloudocistoragesample/ObjectController.java
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/main/resources/application.properties
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/main/resources/application.yaml
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/test/java/com/oracle/cloud/spring/sample/storage/springcloudocistoragesample/SpringCloudOciStorageSampleApplicationTests.java
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/src/test/resources/application-test.properties
  spring-cloud-oci-storage/src/main/java/com/oracle/cloud/spring/storage/OracleStorageProtocolResolver.java
  spring-cloud-oci-storage/src/main/java/com/oracle/cloud/spring/storage/OracleStorageResource.java
  spring-cloud-oci-storage/src/main/java/com/oracle/cloud/spring/storage/StorageImpl.java
  spring-cloud-oci-storage/src/main/java/com/oracle/cloud/spring/storage/StorageLocation.java
  spring-cloud-oci-storage/src/test/java/com/oracle/cloud/spring/storage/OracleStorageProtocolResolverTests.java
  spring-cloud-oci-storage/src/test/java/com/oracle/cloud/spring/storage/OracleStorageResourceTests.java
  spring-cloud-oci-storage/src/test/java/com/oracle/cloud/spring/storage/StorageLocationTests.java
Labels: OCA Verified

#68 Java doc links, typos, and bugs
  docs/src/main/asciidoc/adb.adoc
  docs/src/main/asciidoc/core.adoc
  docs/src/main/asciidoc/db_starters.adoc
  docs/src/main/asciidoc/function.adoc
  docs/src/main/asciidoc/genai.adoc
  docs/src/main/asciidoc/index.adoc
  docs/src/main/asciidoc/logging.adoc
  docs/src/main/asciidoc/notifications.adoc
  docs/src/main/asciidoc/queues.adoc
  docs/src/main/asciidoc/storage.adoc
  docs/src/main/asciidoc/streaming.adoc
  docs/src/main/asciidoc/ucp.adoc
  docs/src/main/asciidoc/vault.adoc
  docs/src/main/spring-cloud-oci.adoc
Labels: documentation, OCA Verified

#67 Refactor Database Starters
  database/starters/oracle-spring-boot-starter-aqjms/pom.xml
  database/starters/oracle-spring-boot-starter-aqjms/src/main/java/com/oracle/spring/aqjms/AqJmsAutoConfiguration.java
  database/starters/oracle-spring-boot-starter-aqjms/src/main/java/com/oracle/spring/aqjms/AqJmsConfigurationProperties.java
  database/starters/oracle-spring-boot-starter-aqjms/src/test/java/com/oracle/spring/aqjms/AqJmsAutoConfigurationTest.java
  database/starters/oracle-spring-boot-starter-aqjms/src/test/java/com/oracle/spring/aqjms/Config.java
  database/starters/oracle-spring-boot-starter-ucp/pom.xml
  database/starters/oracle-spring-boot-starter-ucp/src/main/java/com/oracle/spring/ucp/UCPAutoConfiguration.java
  database/starters/oracle-spring-boot-starter-ucp/src/main/resources/META-INF/spring.factories
  database/starters/oracle-spring-boot-starter-ucp/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  database/starters/oracle-spring-boot-starter-ucp/src/test/java/com/oracle/spring/ucp/Config.java
  database/starters/oracle-spring-boot-starter-ucp/src/test/java/com/oracle/spring/ucp/UCPAutoConfigurationTest.java
  database/starters/pom.xml
Labels: OCA Verified

#70 Removed unused imports
  spring-cloud-oci-adb/src/main/java/com/oracle/cloud/spring/adb/AutonomousDb.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultPropertyLoader.java
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/EmbeddingModelImpl.java
  spring-cloud-oci-storage/src/main/java/com/oracle/cloud/spring/storage/OracleStorageResource.java
Labels: OCA Verified

#72 Email delivery Unit Tests
  docs/src/main/asciidoc/email.adoc
  spring-cloud-oci-email/pom.xml
  spring-cloud-oci-email/src/main/java/com/oracle/cloud/spring/email/EmailDeliveryMailSender.java
  spring-cloud-oci-email/src/test/java/com/oracle/cloud/spring/email/EmailDeliveryJavaMailSenderTest.java
  spring-cloud-oci-email/src/test/java/com/oracle/cloud/spring/email/EmailDeliveryMailSenderTest.java
  spring-cloud-oci-email/src/test/java/com/oracle/cloud/spring/email/EmailTest.java
Labels: OCA Verified

#73 Spring CLI support for OBaaS
  database/spring-cli/catalog/project-catalog.yml
  database/spring-cli/projects/obaas/.gitignore
  database/spring-cli/projects/obaas/.mvn/wrapper/maven-wrapper.jar
  database/spring-cli/projects/obaas/.mvn/wrapper/maven-wrapper.properties
  database/spring-cli/projects/obaas/LICENSE
  database/spring-cli/projects/obaas/README.adoc
  database/spring-cli/projects/obaas/mvnw
  database/spring-cli/projects/obaas/mvnw.cmd
  database/spring-cli/projects/obaas/pom.xml
  database/spring-cli/projects/obaas/src/main/java/com/example/restservice/Application.java
  database/spring-cli/projects/obaas/src/main/java/com/example/restservice/greeting/Greeting.java
  database/spring-cli/projects/obaas/src/main/java/com/example/restservice/greeting/GreetingController.java
  database/spring-cli/projects/obaas/src/main/resources/application.yaml
  database/spring-cli/projects/obaas/src/main/resources/db/changelog/controller.yaml
  database/spring-cli/projects/obaas/src/main/resources/db/changelog/data.sql
  database/spring-cli/projects/obaas/src/main/resources/db/changelog/table.sql
  database/spring-cli/projects/obaas/src/test/java/com/example/restservice/greeting/GreetingControllerTests.java
Labels: OCA Verified

#74 fix url
  database/spring-cli/catalog/project-catalog.yml
Labels: OCA Verified

#75 Spring Cloud Parent Version
  README.md
  pom.xml
  spring-cloud-oci-samples/pom.xml
Labels: OCA Verified

#77 Fix version variable
  docs/src/main/asciidoc/index.adoc
Labels: documentation, OCA Verified

#79 branding update
  .github/workflows/integrationTest.yml
  README.md
  docs/src/main/asciidoc/_attributes.adoc
  docs/src/main/asciidoc/core.adoc
  docs/src/main/asciidoc/email.adoc
  docs/src/main/asciidoc/function.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/index-docinfo.xml
  docs/src/main/asciidoc/index.adoc
  docs/src/main/asciidoc/logging.adoc
  docs/src/main/asciidoc/storage.adoc
  pom.xml
  spring-cloud-oci-adb/pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-email/pom.xml
  spring-cloud-oci-function/pom.xml
  spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci-logging/pom.xml
  spring-cloud-oci-notification/pom.xml
  spring-cloud-oci-queue/pom.xml
  spring-cloud-oci-samples/README.md
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/README.md
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-email/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci-storage/pom.xml
  spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci-vault/pom.xml
Labels: OCA Verified

#82 Add 1.2.0 doc links
  README.md
Labels: documentation, OCA Verified

#83 README update
  README.md
Labels: documentation, OCA Verified

#84 AutoConfiguration Tests
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/email/EmailDeliveryAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/email/MailSenderProperties.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/vault/VaultAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/test/java/com/oracle/cloud/spring/email/EmailDeliveryAutoConfigurationTests.java
  spring-cloud-oci-autoconfigure/src/test/java/com/oracle/cloud/spring/vault/VaultAutoConfigurationTests.java
Labels: OCA Verified

#85 Sync parent pom versions
  pom.xml
  spring-cloud-oci-samples/pom.xml
Labels: OCA Verified

#86 fix adb autoconf bean name, and small readme update
  README.md
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/adb/AutonomousDbAutoConfiguration.java
Labels: OCA Verified

#88 Increment version to 1.3.0-SNAPSHOT
  spring-cloud-oci/docs/pom.xml
  spring-cloud-oci/pom.xml
  spring-cloud-oci/spring-cloud-oci-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci/spring-cloud-oci-core/pom.xml
  spring-cloud-oci/spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci/spring-cloud-oci-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-adb-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-email-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-vault-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci/spring-cloud-oci-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-vault/pom.xml
Labels: OCA Verified

#90 Update SCM URL
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  database/starters/oracle-spring-boot-starter-aqjms/pom.xml
  database/starters/oracle-spring-boot-starter-ucp/pom.xml
  database/starters/pom.xml
  spring-cloud-oci/pom.xml
  spring-cloud-oci/spring-cloud-oci-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci/spring-cloud-oci-core/pom.xml
  spring-cloud-oci/spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci/spring-cloud-oci-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-email-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-vault-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci/spring-cloud-oci-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-vault/pom.xml
Labels: OCA Verified

#91 TEQ Streams uses testcontainers
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  database/spring-cloud-stream-binder-oracle-txeventq/src/main/java/com/oracle/cstream/plsql/OracleDBUtils.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/java/com/oracle/stream/TEQPartitionIT.java
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/resources/application-test.properties
  database/spring-cloud-stream-binder-oracle-txeventq/src/test/resources/init.sql
Labels: OCA Verified
