Repository oracle/spring-cloud-oracle, pull requests merged in 2024-06, with the labels that each got.

#38 Upgrade of OCI SDK and Spring Boot
  pom.xml
Labels: dependencies, OCA Verified

#39 rev version for 1.0.1
  docs/pom.xml
  pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-function/pom.xml
  spring-cloud-oci-logging/pom.xml
  spring-cloud-oci-notification/pom.xml
  spring-cloud-oci-queue/pom.xml
  spring-cloud-oci-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci-storage/pom.xml
  spring-cloud-oci-streaming/pom.xml
Labels: OCA Verified

#40 OKE Workload Identity Authentication
  .gitignore
  README.md
  docs/pom.xml
  docs/src/main/asciidoc/_configprops.adoc
  docs/src/main/asciidoc/core.adoc
  pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/autoconfigure/core/CredentialsProperties.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/autoconfigure/core/CredentialsProvider.java
  spring-cloud-oci-autoconfigure/src/test/java/com/oracle/cloud/spring/autoconfigure/core/CredentialsProviderAutoConfigurationTests.java
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-function/pom.xml
  spring-cloud-oci-logging/pom.xml
  spring-cloud-oci-notification/pom.xml
  spring-cloud-oci-queue/pom.xml
  spring-cloud-oci-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/README.md
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci-storage/pom.xml
  spring-cloud-oci-streaming/pom.xml
Labels: enhancement, OCA Verified

#42 Put back snakeyaml & Spring Cloud 2023.0.2
  pom.xml
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
Labels: enhancement, OCA Verified

#43 OCI GenAI
  docs/src/main/asciidoc/genai.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/index.adoc
  pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/genai/GenAIAutoConfiguration.java
  spring-cloud-oci-autoconfigure/src/main/java/com/oracle/cloud/spring/genai/GenAIProperties.java
  spring-cloud-oci-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-oci-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/ChatModel.java
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/ChatModelImpl.java
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/EmbeddingModel.java
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/EmbeddingModelImpl.java
  spring-cloud-oci-gen-ai/src/main/java/com/oracle/cloud/spring/genai/InferenceRequestType.java
  spring-cloud-oci-gen-ai/src/test/java/com/oracle/cloud/spring/genai/ChatModelTest.java
  spring-cloud-oci-gen-ai/src/test/java/com/oracle/cloud/spring/genai/EmbeddingModelTest.java
  spring-cloud-oci-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/main/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/ChatModelController.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/main/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/EmbeddingModelController.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/main/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/SpringCloudOciGenAISampleApplication.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/main/resources/application.properties
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/ChatIT.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/CohereChatIT.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/EmbeddingIT.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/java/com/oracle/cloud/spring/sample/genai/springcloudocigenaisample/LLamaChatIT.java
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/resources/application-chat-cohere.properties
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/resources/application-chat-llama.properties
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/src/test/resources/application-embedding.properties
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
Labels: OCA Verified

#45 Fix GenAI Unit Tests
  spring-cloud-oci-gen-ai/src/test/java/com/oracle/cloud/spring/genai/ChatModelTest.java
Labels: OCA Verified

#46 OCI GenAI README
  README.md
  spring-cloud-oci-samples/README.md
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/README.md
Labels: OCA Verified

#48 Upgrade SB and OCI versions to fix CVE
  pom.xml
Labels: OCA Verified

#49 Add pom headers
  docs/pom.xml
  pom.xml
  spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci-core/pom.xml
  spring-cloud-oci-function/pom.xml
  spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci-logging/pom.xml
  spring-cloud-oci-notification/pom.xml
  spring-cloud-oci-queue/pom.xml
  spring-cloud-oci-samples/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci-samples/spring-cloud-oci-vault-sample/pom.xml
  spring-cloud-oci-starters/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci-storage/pom.xml
  spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci-vault/pom.xml
Labels: OCA Verified
