Repository oracle/spring-cloud-oracle, pull requests merged in 2025-05, with the labels that each got.

#183 Hikari to UCP Recipe
  recipes/hikariucp/.gitignore
  recipes/hikariucp/README.md
  recipes/hikariucp/pom.xml
  recipes/hikariucp/src/main/com/oracle/cloud/recipes/hikariucp/ConvertMsToSecondsInPropertiesRecipe.java
  recipes/hikariucp/src/main/com/oracle/cloud/recipes/hikariucp/ConvertMsToSecondsInYamlRecipe.java
  recipes/hikariucp/src/main/resources/META-INF/rewrite/rewrite.yml
  recipes/hikariucp/src/test/oracle/com/cloud/recipes/hikariucp/ChangePropertyValueTest.java
Labels: OCA Verified, Recipes

#193 Update versions for Spring CLI
  spring-cli/projects/obaas/pom.xml
Labels: OCA Verified

#194 Flatten the docu menu
  spring-cloud-oci/docs/src/main/asciidoc/aqjms.adoc
  spring-cloud-oci/docs/src/main/asciidoc/db_starters.adoc
  spring-cloud-oci/docs/src/main/asciidoc/getting-started.adoc
  spring-cloud-oci/docs/src/main/asciidoc/index.adoc
  spring-cloud-oci/docs/src/main/asciidoc/jsoncollection.adoc
  spring-cloud-oci/docs/src/main/asciidoc/ucp.adoc
  spring-cloud-oci/docs/src/main/asciidoc/wallet.adoc
Labels: documentation, OCA Verified

#197 Release 1.4.2
  database/spring-cloud-stream-binder-oracle-txeventq/pom.xml
  spring-cloud-oci/docs/pom.xml
  spring-cloud-oci/pom.xml
  spring-cloud-oci/spring-cloud-oci-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-autoconfigure/pom.xml
  spring-cloud-oci/spring-cloud-oci-core/pom.xml
  spring-cloud-oci/spring-cloud-oci-dependencies/pom.xml
  spring-cloud-oci/spring-cloud-oci-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-adb-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-common-samples-utils/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-email-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-function-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-gen-ai-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-logging-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-nosql-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-notification-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-queue-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-storage-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-streaming-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-samples/spring-cloud-oci-vault-sample/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-adb/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-email/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-function/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-gen-ai/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-logging/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-nosql/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-notification/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-queue/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter-vault/pom.xml
  spring-cloud-oci/spring-cloud-oci-starters/spring-cloud-oci-starter/pom.xml
  spring-cloud-oci/spring-cloud-oci-storage/pom.xml
  spring-cloud-oci/spring-cloud-oci-streaming/pom.xml
  spring-cloud-oci/spring-cloud-oci-vault/pom.xml
Labels: OCA Verified

#200 Docu updates
  1.4.1/reference/html/adb.html
  1.4.1/reference/html/appendix.html
  1.4.1/reference/html/configuration.html
  1.4.1/reference/html/core.html
  1.4.1/reference/html/db_starters.html
  1.4.1/reference/html/email.html
  1.4.1/reference/html/function.html
  1.4.1/reference/html/genai.html
  1.4.1/reference/html/getting-started.html
  1.4.1/reference/html/index.html
  1.4.1/reference/html/logging.html
  1.4.1/reference/html/nosql.html
  1.4.1/reference/html/notifications.html
  1.4.1/reference/html/queues.html
  1.4.1/reference/html/storage.html
  1.4.1/reference/html/streaming.html
  1.4.1/reference/html/vault.html
  latest/reference/html/adb.html
  latest/reference/html/appendix.html
  latest/reference/html/configuration.html
  latest/reference/html/core.html
  latest/reference/html/db_starters.html
  latest/reference/html/email.html
  latest/reference/html/function.html
  latest/reference/html/genai.html
  latest/reference/html/getting-started.html
  latest/reference/html/index.html
  latest/reference/html/logging.html
  latest/reference/html/nosql.html
  latest/reference/html/notifications.html
  latest/reference/html/queues.html
  latest/reference/html/storage.html
  latest/reference/html/streaming.html
  latest/reference/html/vault.html
Labels: documentation, OCA Verified

#202 Database starter javadocs
  database/starters/Makefile
  database/starters/pom.xml
Labels: documentation, OCA Verified

#204 OSON Kafka Serializers
  database/spring-cloud-stream-binder-oracle-txeventq/spring-cloud-stream-binder-txeventq-sample/pom.xml
  database/starters/oracle-spring-boot-json-data-tools/pom.xml
  database/starters/oracle-spring-boot-json-data-tools/src/main/java/com/oracle/spring/json/JsonCollectionsAutoConfiguration.java
  database/starters/oracle-spring-boot-json-data-tools/src/main/java/com/oracle/spring/json/kafka/OSONDeserializer.java
  database/starters/oracle-spring-boot-json-data-tools/src/main/java/com/oracle/spring/json/kafka/OSONKafkaSerializationFactory.java
  database/starters/oracle-spring-boot-json-data-tools/src/main/java/com/oracle/spring/json/kafka/OSONSerializer.java
  database/starters/oracle-spring-boot-starter-samples/oracle-spring-boot-sample-json-events/src/main/java/com/oracle/database/spring/jsonevents/OKafkaConfiguration.java
Labels: OCA Verified
